version: 2
jobs:   
  build:
    machine: true
    steps:
      - add_ssh_keys:
          fingerprints: 
            - "3c:d3:a8:ad:a7:66:d9:58:f7:90:1a:fb:b5:a3:cf:95"
      - checkout
      - run: docker login -u $DOCKER_USER -p $DOCKER_PASS
      - run: docker build -t pablostella/ci_cd:$CIRCLE_SHA1 .
      - run: docker push pablostella/ci_cd:$CIRCLE_SHA1
      - run: ssh -o StrictHostKeyChecking=no root@docker.terobit.com "/bin/bash /root/docker/deploy.sh $CIRCLE_SHA1"
